package co.edu.unicauca.mycompany.projects.presentation;

import co.edu.unicauca.mycompany.projects.domain.entities.Student;
import java.awt.Color;
import java.awt.Font;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.StandardBarPainter;
import org.jfree.data.category.DefaultCategoryDataset;


/**
 * @file GUIDashboardEstudiante.java
 * @brief Interfaz gráfica del panel de control para estudiantes.
 *
 * Esta clase representa la ventana principal del estudiante, donde puede visualizar 
 * la cantidad de proyectos realizados, en curso y finalizados, además de otras 
 * funcionalidades relacionadas con la gestión de proyectos académicos.
 *
 * @author Paula Munoz
 */
public class GUIDashboardEstudiante extends javax.swing.JFrame {
    /**
     * Objeto que representa al estudiante que está utilizando la interfaz.
     */
    private Student estudiante;
    
    /**
     * @brief Constructor de la clase.
     *
     * Inicializa los componentes de la interfaz gráfica del panel de control 
     * del estudiante y configura los elementos visuales.
     *
     * @param estudiante Objeto de tipo Student que contiene la información del estudiante.
     */
    public GUIDashboardEstudiante(Student estudiante) {
        // Asigna el estudiante recibido por parámetro a la variable de instancia
        this.estudiante = estudiante;
        // Hace visible la ventana
        this.setVisible(true);
        
        // Llamada al método que inicializa los componentes de la interfaz gráfica
        initComponents();
        // Llamada al método que genera y muestra la gráfica de proyectos
        mostrarGrafico();
        // Configura la ventana para que aparezca centrada en la pantalla
        setLocationRelativeTo(null);
        // Bloquea el redimensionamiento de la ventana
        setResizable(false);

        // Establece el texto del botón de inicio con el identificador del estudiante
        btnInicio.setText("Estudiante " + estudiante.getId());
        // Muestra un mensaje de bienvenida con el nombre del estudiante en el título
        lblTitulo.setText("Bienvenido " + estudiante.getNombreStudent());
        // Muestra el correo electrónico del estudiante en la interfaz
        lblCorreo.setText(estudiante.getCorreo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblCorreo = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        btnProyectos = new javax.swing.JButton();
        btnPostular = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jPanelGrafico = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jPanel4.setBackground(new java.awt.Color(90, 111, 228));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCorreo.setText("tuEstudiante@gmail.com");
        jPanel4.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 150, 190, -1));

        btnInicio.setBackground(new java.awt.Color(90, 111, 228));
        btnInicio.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Estudiante X");
        btnInicio.setBorder(null);
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setFocusPainted(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        jPanel4.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 210, 50));

        btnProyectos.setBackground(new java.awt.Color(90, 111, 228));
        btnProyectos.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnProyectos.setForeground(new java.awt.Color(255, 255, 255));
        btnProyectos.setText("Mis proyectos");
        btnProyectos.setBorder(null);
        btnProyectos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProyectosActionPerformed(evt);
            }
        });
        jPanel4.add(btnProyectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 210, 50));

        btnPostular.setBackground(new java.awt.Color(90, 111, 228));
        btnPostular.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnPostular.setForeground(new java.awt.Color(255, 255, 255));
        btnPostular.setText("Postularme");
        btnPostular.setBorder(null);
        btnPostular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPostular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostularActionPerformed(evt);
            }
        });
        jPanel4.add(btnPostular, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 210, 50));

        lblTitulo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(38, 42, 65));
        lblTitulo.setText("Bienvenido Estudiante X");

        jPanelGrafico.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelGraficoLayout = new javax.swing.GroupLayout(jPanelGrafico);
        jPanelGrafico.setLayout(jPanelGraficoLayout);
        jPanelGraficoLayout.setHorizontalGroup(
            jPanelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
        );
        jPanelGraficoLayout.setVerticalGroup(
            jPanelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addComponent(jPanelGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitulo)
                .addGap(26, 26, 26)
                .addComponent(jPanelGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        dispose();
        GUIDashboardEstudiante instancia = new GUIDashboardEstudiante(estudiante);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProyectosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProyectosActionPerformed

    private void btnPostularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostularActionPerformed
        this.setVisible(false); // Oculta el frame sin cerrarlo
        GUIProyectosDisponibles instancia = new GUIProyectosDisponibles(estudiante); // Crea una instancia del otro frame
        instancia.setVisible(true); // Volver visible el otro frame
    }//GEN-LAST:event_btnPostularActionPerformed

    /**
     * @brief Muestra un gráfico de barras con la cantidad de proyectos en diferentes estados.
     *
     * Esta función crea un conjunto de datos con el total de proyectos, 
     * los proyectos en curso y los finalizados. Luego, genera un gráfico 
     * de barras utilizando la biblioteca JFreeChart y lo añade al panel 
     * de gráficos en la interfaz.
     */
    private void mostrarGrafico() {
        // Crear el conjunto de datos para el gráfico
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(10, "Proyectos", "Total");       // Agrega el total de proyectos
        dataset.setValue(4, "Proyectos", "En Curso");     // Agrega los proyectos en curso
        dataset.setValue(6, "Proyectos", "Finalizados");  // Agrega los proyectos finalizados 
       
        // Crear el gráfico de barras con los datos proporcionados
        JFreeChart chart = ChartFactory.createBarChart(
                "Cantidad de Proyectos",  // Establece el título del gráfico
                "Estado",                 // Etiqueta del eje X (categorías de proyectos)
                "Cantidad",               // Etiqueta del eje Y (cantidad de proyectos)
                dataset,                  // Conjunto de datos del gráfico
                PlotOrientation.VERTICAL, // Orientación del gráfico (vertical)
                false,  // No muestra la leyenda
                true,   // Activa herramientas de ayuda
                false   // No habilita URL en cada barra
        );

        // Configurar el área donde se dibujan las barras
        CategoryPlot plot = chart.getCategoryPlot();
        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        // Asigna un color personalizado a las barras del gráfico
        renderer.setSeriesPaint(0, new Color(90, 111, 228));
        // Elimina el efecto 3D del gráfico para un diseño plano
        renderer.setBarPainter(new StandardBarPainter());
        // Configura el fondo del gráfico en color blanco
        plot.setBackgroundPaint(Color.WHITE); 
        plot.setOutlineVisible(false); // Oculta el borde del gráfico
        // Configura la fuente y el estilo del título del gráfico
        chart.getTitle().setFont(new Font("Segoe UI", Font.BOLD, 18));

        // Crear un panel para mostrar el gráfico y ajustarlo a la interfaz
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setSize(jPanelGrafico.getWidth(), jPanelGrafico.getHeight()); // Ajusta el tamaño del panel
        jPanelGrafico.add(chartPanel); // Agrega el gráfico al panel de la interfaz
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnPostular;
    private javax.swing.JButton btnProyectos;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelGrafico;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
