package co.edu.unicauca.mycompany.projects.presentation;

import co.edu.unicauca.mycompany.projects.domain.entities.Project;
import co.edu.unicauca.mycompany.projects.domain.entities.Student;
import javax.swing.table.DefaultTableModel;


/**
 * @file GUIProyectosDisponibles.java
 * @brief Interfaz gráfica del panel para postularse a proyectos.
 * 
 * Esta clase representa una ventana del estudiante, donde puede visualizar 
 * los proyectos disponibles y puede postularse a ellos 
 * 
 * @author Paula Munoz
 */
public class GUIProyectosDisponibles extends javax.swing.JFrame {
    private Student estudiante;
    
    /**
     * @brief Constructor de la clase.
     *
     * Inicializa los componentes de la interfaz gráfica del panel visualizacion
     * y postulacion de los proyectos disponibles a postularse
     */
    public GUIProyectosDisponibles(Student estudiante) {
        // Inicializar componentes
        initComponents();
        // Inicializar la tabla
        crearTabla();
        // Configurar el frame en el centro
        setLocationRelativeTo(null);
        // Configurar el frame para que no se pueda modificar
        setResizable(false);
        this.estudiante = estudiante;
        this.setVisible(true);
        btnInicio.setText("Estudiante "+estudiante.getId());
        lblCorreo.setText(estudiante.getCorreo());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnPostular = new javax.swing.JButton();
        btnProyectos = new javax.swing.JButton();
        lblCorreo = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEstudiante = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jPanel4.setBackground(new java.awt.Color(90, 111, 228));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPostular.setBackground(new java.awt.Color(75, 99, 225));
        btnPostular.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnPostular.setForeground(new java.awt.Color(255, 255, 255));
        btnPostular.setText("Postularme");
        btnPostular.setBorder(null);
        btnPostular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPostular.setFocusPainted(false);
        btnPostular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostularActionPerformed(evt);
            }
        });
        jPanel4.add(btnPostular, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 210, 50));

        btnProyectos.setBackground(new java.awt.Color(90, 111, 228));
        btnProyectos.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnProyectos.setForeground(new java.awt.Color(255, 255, 255));
        btnProyectos.setText("Mis proyectos");
        btnProyectos.setBorder(null);
        btnProyectos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProyectos.setFocusPainted(false);
        btnProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProyectosActionPerformed(evt);
            }
        });
        jPanel4.add(btnProyectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 210, 50));

        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCorreo.setText("tuEstudiante@gmail.com");
        jPanel4.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 190, -1));

        btnInicio.setBackground(new java.awt.Color(90, 111, 228));
        btnInicio.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Estudiante X");
        btnInicio.setBorder(null);
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setFocusPainted(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        jPanel4.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 210, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(38, 42, 65));
        jLabel10.setText("Postularme en proyectos");

        jTableEstudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Empresa", "Nombre Proyecto", "Fecha", "Acciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEstudiante.setGridColor(new java.awt.Color(204, 204, 204));
        jTableEstudiante.setRowHeight(45);
        jTableEstudiante.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTableEstudiante);
        jTableEstudiante.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPostularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostularActionPerformed
        dispose();
        GUIProyectosDisponibles instancia = new GUIProyectosDisponibles(estudiante);
    }//GEN-LAST:event_btnPostularActionPerformed

    private void btnProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProyectosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProyectosActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        new GUIDashboardEstudiante(estudiante).setVisible(true); // Reabre el JFrame
        dispose(); // Cierra el segundo JFrame
    }//GEN-LAST:event_btnInicioActionPerformed

    /**
    * @brief Actualiza la configuración de la tabla de estudiantes.
    *
    * Este método configura la columna 3 de la tabla `jTableEstudiante`,
    * estableciendo su tamaño fijo y asignando un renderizador y un editor de celdas personalizados.
    */
    private void crearTabla() {
        //Establece el ancho mínimo, máximo y preferido de la columna 3 en 225 píxeles.
        this.jTableEstudiante.getColumnModel().getColumn(3).setMinWidth(225); // Ancho mínimo de la columna.
        this.jTableEstudiante.getColumnModel().getColumn(3).setMaxWidth(225); // Ancho máximo de la columna.
        this.jTableEstudiante.getColumnModel().getColumn(3).setPreferredWidth(225); // Ancho preferido de la columna.

        // Asigna un renderizador personalizado a la columna 3.
        //Permite que se visualicen componentes como botones dentro de la tabla.
        this.jTableEstudiante.getColumnModel().getColumn(3).setCellRenderer(new TableActionCellRenderEstudiante());

        // Asigna un editor de celdas personalizado a la columna 3.
        // Permite la interacción con los botones dentro de la celda
        this.jTableEstudiante.getColumnModel().getColumn(3).setCellEditor(new TableActionCellEditorEstudiante(estudiante));

        // Confugurar el MultilineCell en cada fila
        for(int i=0;i<jTableEstudiante.getColumnCount()-1;i++){
            jTableEstudiante.getColumnModel().getColumn(i).setCellRenderer(new MultiLineCellRenderer()); 
        }
        jTableEstudiante.setRowHeight(50);
        
        // For para ingresar los datos desde la bd y llamando nuevoProject
        DefaultTableModel modelo = (DefaultTableModel) jTableEstudiante.getModel();
        modelo.addRow(new Object[]{"Empresa A", "Proyecto X", "01", "Acciones"});
        modelo.addRow(new Object[]{"Empresa B", "Proyecto Y", "15", "Acciones"});
        modelo.addRow(new Object[]{"Empresa C", "Proyecto Z", "2", "Acciones"});
    }
    
    public void nuevoProject(Project proyecto) {
        // Obtener el modelo de la tabla
        DefaultTableModel modelo = (DefaultTableModel) jTableEstudiante.getModel();
        // Agregar una nueva fila con datos del proyecto
        modelo.addRow(new Object[]{proyecto.getProId(), proyecto.getProTitle(), proyecto.getProDeadLine(), "Acciones"});
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnPostular;
    private javax.swing.JButton btnProyectos;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEstudiante;
    private javax.swing.JLabel lblCorreo;
    // End of variables declaration//GEN-END:variables
}
