package co.edu.unicauca.mycompany.projects.presentation;

import co.edu.unicauca.mycompany.projects.domain.entities.Project;
import co.edu.unicauca.mycompany.projects.domain.entities.Student;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JWindow;
import javax.swing.Timer;
import javax.swing.border.LineBorder;

/**
 * @file GUIPostularse.java
 * @brief Interfaz gráfica para postularse a un proyecto.
 *
 * Esta clase representa la ventana donde un estudiante puede postularse a un proyecto
 * académico. Permite al usuario confirmar o cancelar su postulación.
 *
 * @author Ana Sofia, Paula Munoz
 */
public class GUIPostularse extends javax.swing.JFrame {
    /**
     * Proyecto al que el estudiante desea postularse.
     */
    private Project proyecto;
    
    /**
     * Estudiante que está realizando la postulación.
     */
    private Student estudiante;
    
    /**
     * @brief Constructor de la clase.
     *
     * Inicializa los componentes de la interfaz y configura la ventana.
     *
     * @param proyecto Proyecto al que el estudiante desea postularse.
     * @param estudiante Estudiante que está realizando la postulación.
     */
    public GUIPostularse(Project proyecto, Student estudiante) {
        // Asignar los valores recibidos a las variables de instancia
        this.proyecto = proyecto;
        this.estudiante = estudiante;
        
        // Inicializar componentes de la interfaz gráfica
        initComponents();
        
        // Configurar la ventana para que aparezca centrada en la pantalla
        setLocationRelativeTo(null);
        // Bloquear el redimensionamiento de la ventana
        setResizable(false);
        // Configurar para que la ventana se cierre sin terminar la aplicación
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnAceptar.setBackground(new java.awt.Color(90, 111, 228));
        btnAceptar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.setFocusPainted(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setFocusPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(38, 42, 65));
        jLabel11.setText("¿Desea enviar");

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(38, 42, 65));
        jLabel12.setText("la solicitud?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @brief Evento que se ejecuta cuando el usuario hace clic en "Aceptar".
     *
     * Cierra la ventana actual y muestra un mensaje emergente indicando que la postulación fue enviada.
     *
     * @param evt Evento de acción generado por el botón "Aceptar".
     */
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // Cierra la ventana actual
        dispose();
        
        // Crear una ventana emergente sin bordes
        JWindow window = new JWindow();
        
        // Crear una etiqueta con el mensaje de confirmación
        JLabel label = new JLabel("Postulación enviada al proyecto " + proyecto.getProTitle(), JLabel.CENTER);
        label.setOpaque(true); // Hacer que la etiqueta tenga un fondo visible
        label.setBackground(Color.WHITE); // Establecer el fondo en color blanco
        label.setBorder(new LineBorder(new Color(90, 111, 228), 2)); // Establecer un borde azul
        label.setForeground(Color.BLACK); // Color del texto
        label.setFont(new Font("Segoe UI Semibold", Font.BOLD, 14)); // Establecer la fuente

        // Agregar la etiqueta a la ventana emergente
        window.getContentPane().add(label);
        // Definir el tamaño de la ventana emergente
        window.setSize(500, 50);
        // Posicionar la ventana en la pantalla
        window.setLocation(482, 675);
        
        // Configurar un temporizador para cerrar la ventana emergente automáticamente en 2 segundos
        new Timer(2000, e -> window.dispose()).start();
        
        // Hacer visible la ventana emergente
        window.setVisible(true);
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @brief Evento que se ejecuta cuando el usuario hace clic en "Cancelar".
     *
     * Cierra la ventana sin realizar ninguna acción.
     *
     * @param evt Evento de acción generado por el botón "Cancelar".
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // Cierra la ventana actual sin realizar cambios
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
