/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.edu.unicauca.mycompany.projects.presentation;

import co.edu.unicauca.mycompany.projects.domain.entities.Project;
import co.edu.unicauca.mycompany.projects.domain.entities.Student;

/**
 * @file PanelActionEstudiante.java
 * @brief Panel de acciones para estudiantes.
 *
 * Este panel permite a un estudiante ver detalles de un proyecto y postularse a él.
 *
 * @author Ana Sofia, Paula Munoz
 */
public class PanelActionEstudiante extends javax.swing.JPanel {
    /**
     * Proyecto asociado a las acciones del panel.
     */
    private Project proyecto;
    
    /**
     * Estudiante que interactúa con el panel.
     */
    private Student estudiante;
    
    /**
     * @brief Constructor de la clase.
     *
     * Inicializa los componentes de la interfaz y configura eventos de botones.
     *
     * @param proyecto Proyecto asociado al estudiante.
     * @param estudiante Estudiante que interactúa con el panel.
     */
    public PanelActionEstudiante(Project proyecto, Student estudiante) {
        // Asignar los valores recibidos a las variables de instancia
        this.proyecto = proyecto;
        this.estudiante = estudiante;
        
        // Inicializar componentes de la interfaz gráfica
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPostularse = new javax.swing.JButton();
        btnDetallesEst = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnPostularse.setBackground(new java.awt.Color(22, 192, 152));
        btnPostularse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPostularse.setForeground(new java.awt.Color(255, 255, 255));
        btnPostularse.setText("Postularse");
        btnPostularse.setFocusPainted(false);
        btnPostularse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostularseActionPerformed(evt);
            }
        });

        btnDetallesEst.setBackground(new java.awt.Color(41, 64, 211));
        btnDetallesEst.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDetallesEst.setForeground(new java.awt.Color(255, 255, 255));
        btnDetallesEst.setText("Detalles");
        btnDetallesEst.setFocusPainted(false);
        btnDetallesEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesEstActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDetallesEst, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPostularse)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetallesEst)
                    .addComponent(btnPostularse))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @brief Evento que se ejecuta al hacer clic en "Detalles".
     *
     * Abre una nueva ventana con los detalles del proyecto.
     *
     * @param evt Evento de acción generado por el botón "Detalles".
     */
    private void btnDetallesEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesEstActionPerformed
        // Crear una nueva ventana de detalles del proyecto y mostrarla
        GUIVerDetalles detallesFrame = new GUIVerDetalles(proyecto);
        // Mostrar la ventana de los detalles del proyecto
        detallesFrame.setVisible(true);
    }//GEN-LAST:event_btnDetallesEstActionPerformed

    /**
     * @brief Evento que se ejecuta al hacer clic en "Postularse".
     *
     * Verifica si el estudiante ya está postulado y, si no, abre la interfaz de postulación.
     *
     * @param evt Evento de acción generado por el botón "Postularse".
     */
    private void btnPostularseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostularseActionPerformed
        // Verificar en la base de datos que el estudiante no se haya postulado antes
        // Crear una nueva ventana de detalles del proyecto y mostrarla
        GUIPostularse objpostularse = new GUIPostularse(proyecto, estudiante);
        // Mostrar la ventana de postulación
        objpostularse.setVisible(true);
    }//GEN-LAST:event_btnPostularseActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetallesEst;
    private javax.swing.JButton btnPostularse;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
